FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Make directories
RUN mkdir .data
RUN mkdir components
RUN mkdir public
RUN mkdir views

# Bundle app source
COPY .data/ /usr/src/app/.data/
COPY components/ /usr/src/app/components/
COPY public/ /usr/src/app/public/
COPY skills/ /usr/src/app/skills/
COPY views/ /usr/src/app/views/
COPY .env /usr/src/app
COPY bot.js /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]
